server:
  port: 8081
feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 30000
  okhttp:
    enabled: true
app:
  feignclient:
    order-management-url: http://localhost:8080
spring:
  cache:
    type: redis
    redis:
      timeToLive: 10m
  datasource:
    url: jdbc:postgresql://localhost:9910/user-management
    username: sonar
    password: sonar
  redis:
    host: localhost
    port: 9911 # Redis服务器连接端口
  lettuce:
    pool:
      max-active: 8 # 连接池最大连接数
      max-idle: 8 # 连接池最大空闲连接数
      min-idle: 0 # 连接池最小空闲连接数
      max-wait: 10000ms # 连接池最大阻塞等待时间，负值表示没有限制
      timeBetweenEvictionRuns: 10m
